Upgrade select packages
codefordenver/members pull request #118
Opened 2018-01-30 02:38 UTC by fredmon3

This PR closes #73 

#### What does this PR do?
This PR upgrades select packages to eliminate known vulnerabilities.

#### How does this PR make you feel? [:link:](http://giphy.com/categories/emotions/)

![](https://media.giphy.com/media/4JhyL6iRXrzQA/giphy.gif)

2018-01-30 02:41 UTC, nlkluth approved these changes

2018-01-30 02:43 UTC, nlkluth requested changes
Uh oh

2018-01-30 03:04 UTC, KeynesYouDigIt commented
Does this cover #73 ? I see alot of changes to tar just wanted to check and see if I should look into it

2018-02-04 04:13 UTC, wdoug commented
What is the status of this @nlkluth and @fredmon3? All I see is the "Uh oh" comment. Was the graphcool framework tested with the upgraded version? 

Also, the `graphcool` project we use has been renamed to [graphcool-framework](https://github.com/graphcool/graphcool-framework#quickstart). We might want to update those references.

2018-03-06 02:14 UTC, closed without merging