Add ability to edit projects
codefordenver/members pull request #146
Opened 2018-02-24 06:14 UTC by wdoug

This PR closes #143 

#### What does this PR do?

- Adds the ability to edit projects

#### How does this PR make you feel? [:link:](http://giphy.com/categories/emotions/)

![](https://media.giphy.com/media/6anKlIA7ZKXYc/giphy.gif)

2018-02-24 06:17 UTC, wdoug commented
I'm not super happy with the implementation of this right now. I'd like to refactor things so there is less boilerplate. I'm not sure exactly what path I want to go down for that though. Maybe adding [redux-form](https://redux-form.com) -- on one hand it seems a little silly to add redux just for forms, but on the other hand, it also opens up the door to using some redux ecosystem stuff, which could possibly make it easy to do things like persisting partially edited forms to local storage.

2018-02-26 02:20 UTC, wdoug commented
Alright, I've refactored things, and while I think we can continue to make things better, they are way better than they started out, and I feel generally comfortable merging things as they stand now

2018-02-27 03:11 UTC, sungbae requested changes
I think this is pretty solid. I just left a few questions!

2018-02-27 03:11 UTC, sungbae commented on src/sections/ProjectSection.js
> +    editing
Is this supposed to be a property? What does this do exactly?

2018-02-27 03:11 UTC, sungbae commented on src/sections/ProjectSection.js
> +        <EditableText value={name} label="Title" name="name" {...commonProps} />
I guess you're injecting the elements into here (e.g. `{...commonProps}`)? But I still don't understand what `editing` is exactly...

2018-02-27 03:11 UTC, sungbae commented on src/utils/withCreatePage.js
> +            ...state.formData,
Is this how you can copy/paste the properties from `state.formData` here?

2018-02-27 03:11 UTC, sungbae commented on src/utils/withEditPage.js
> +        if (!this.props.formData) {
Couldn't this always be false? If `this.props.formData` is initialized as `{}`.

2018-02-27 03:11 UTC, sungbae commented on src/utils/withViewPage.js
> +        if (!formData) {
Same concern as the comment in `withEditPage.js`. If the `formData` is initialized already as `{}`, couldn't this always be false?

2018-02-27 03:28 UTC, wdoug commented on src/sections/ProjectSection.js
> +    editing
It is shorthand for `editing: editing` in the object

2018-02-27 03:31 UTC, wdoug commented on src/utils/withCreatePage.js
> +            ...state.formData,
It is a way of copying the keys and values from `formData` into this new object

2018-02-27 03:35 UTC, wdoug commented on src/utils/withEditPage.js
> +        if (!this.props.formData) {
It is passed in as a prop from above, which, as it is coded currently, initializes it as `undefined`

2018-02-27 03:36 UTC, sungbae approved these changes

2018-02-27 03:45 UTC, rufusasterisk commented
Tested on the deploy/netlify link

##### Add new event
Adding a new event from /projects/create successfully created an event - link was visible on /projects
The event persisted after navigating away
The event body supports markdown

##### Edit existing event
Event saved changes made through edit process
Changes persisted after navigating away

2018-02-27 03:46 UTC, merged