Debug CRA Tests
codefordenver/members pull request #170
Opened 2018-03-06 03:24 UTC by fredmon3

This PR closes #112 

#### What does this PR do?

Adds CRA test debugging.

#### How does this PR make you feel? [:link:](http://giphy.com/categories/emotions/)

![](https://i.imgur.com/zN8Vley.gif)

2018-03-08 01:49 UTC, wdoug commented
@fredmon3 I get the same errors when trying to run this that travis ci is failing with:
```sh
$ npm test
> members@0.1.0 test /home/travis/build/codefordenver/members
> react-scripts test --env=jsdom
 FAIL  src/App.test.js
  ● Test suite failed to run
    /home/travis/build/codefordenver/members/node_modules/graphql/language/printer.mjs:8
    import { visit } from './visitor';
    ^^^^^^
    
    SyntaxError: Unexpected token import
      
      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/ScriptTransformer.js:289:17)
      at node_modules/apollo-link/lib/bundle.umd.js:2:141
      at Object.<anonymous> (node_modules/apollo-link/lib/bundle.umd.js:5:2)
Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.248s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
The command "npm test" exited with 1.
```

2018-03-08 02:04 UTC, wdoug commented
I went ahead and also updated the Create React App docs for this PR as we update `react-scripts`

2018-04-10 22:34 UTC, wdoug commented
@fredmon3 this PR now only has the updated docs. The `.vscode` changes have disappeared for some reason

2018-04-13 01:14 UTC, wdoug requested changes
Let's add back the `.vscode` stuff for this

2018-04-17 02:44 UTC, fredmon3 commented
@wdoug How's it looking?

2018-04-20 01:22 UTC, wdoug commented on .vscode/launch.json
> +        "name": "Chrome",
What does the chrome debugger do?

2018-04-20 01:28 UTC, wdoug commented on .vscode/launch.json
> +        "name": "Chrome",
Nevermind, I see in the `CreateReactApp.md` document

2018-04-20 01:29 UTC, wdoug approved these changes
Looks good. It might be nice to include a note in the readme how to use the vscode debugger. Maybe just copying some of the text from the CreateReactApp.md file, or at least linking to it

2018-04-20 03:06 UTC, merged